//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messenger.DataLayer.Sql.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Messenger.DataLayer.Sql.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Returns &quot;TRUE&quot;, if finds a personal chat of user with himself.
        ///-- Returns &quot;FALSE&quot;, if such chat was not found.
        ///
        ///DECLARE @Enumerator TABLE (id uniqueidentifier)
        ///
        ///INSERT INTO @Enumerator
        ///SELECT [ChatId]
        ///FROM [ChatMembers]
        ///WHERE [UserId] = @user 
        ///
        ///DECLARE @id uniqueidentifier
        ///DECLARE @numOfMembers int
        ///
        ///WHILE EXISTS(SELECT 1 FROM @Enumerator)
        ///BEGIN
        ///     SELECT TOP 1 @id = id FROM @Enumerator 
        ///
        ///	 SELECT @numOfMembers = COUNT([UserId]) 
        ///	 FROM [ChatMembers]
        ///	 WHERE [ChatId] = @id
        ///
        ///	 IF (@n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OnePersonChatExists {
            get {
                return ResourceManager.GetString("OnePersonChatExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Returns &quot;TRUE&quot;, if finds a personal chat between users with given ids.
        ///-- Returns &quot;FALSE&quot;, if such chat was not found.
        ///
        ///IF EXISTS
        ///(
        ///	SELECT [ChatId]
        ///	FROM [ChatMembers], 
        ///	(
        ///		SELECT [Id]
        ///		FROM [Chat],
        ///		(
        ///			SELECT [ChatId]	
        ///			FROM [ChatMembers]
        ///			WHERE [UserId] = @user1
        ///		) AS [UserChats]
        ///		WHERE 
        ///		(
        ///			[Id] = [ChatId] AND
        ///			[Type] = &apos;personal&apos;
        ///		)
        ///	) AS [UserPersonalChats]
        ///	WHERE 
        ///	(
        ///		[ChatId] = [Id] AND
        ///		[UserId] = @user2
        ///	)
        ///)
        ///	SELECT &apos;TRUE&apos; AS [RESULT]
        ///ELSE
        ///	SELEC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TwoPersonsChatExists {
            get {
                return ResourceManager.GetString("TwoPersonsChatExists", resourceCulture);
            }
        }
    }
}
